/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaz;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author donco
 */
public class Busqueda extends javax.swing.JFrame {

    /**
     * Creates new form Busqueda
     */
    DefaultTableModel modelo;
    public Busqueda() {
        initComponents();
        campoNombre.setEnabled(false);
        campoProfesion.setEnabled(false);
        campoPromedio.setEnabled(false);
        modelo=new DefaultTableModel();
        modelo.addColumn("Nombre");
        modelo.addColumn("Profesion");
        modelo.addColumn("Promedio");
        this.jTable1.setModel(modelo);
        jButton2.setEnabled(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        campoNombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        campoProfesion = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        campoPromedio = new javax.swing.JTextField();
        mayorCheck = new javax.swing.JCheckBox();
        menorCheck = new javax.swing.JCheckBox();
        igualCheck = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nombre", "Profesion", "Promedio", "Nombre/Profesion", "Nombre/Promedio", "Profesion/Nombre", "Profesion/Promedio" }));

        jButton1.setText("Confirmar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Nombre a buscar");

        jLabel2.setText("Profesion a buscar");

        jLabel3.setText("Promedio a buscar");

        jLabel4.setText("Criterios de promedio");

        mayorCheck.setText("Mayor que");
        mayorCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mayorCheckActionPerformed(evt);
            }
        });

        menorCheck.setText("Menor que");
        menorCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menorCheckActionPerformed(evt);
            }
        });

        igualCheck.setText("Igual a");
        igualCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                igualCheckActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton2.setText("Buscar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(126, 126, 126)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(campoNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                                    .addComponent(campoProfesion)
                                    .addComponent(campoPromedio)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(mayorCheck, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(menorCheck, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(igualCheck, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 484, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(campoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(campoProfesion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(campoPromedio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(mayorCheck)
                    .addComponent(menorCheck)
                    .addComponent(igualCheck))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(102, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mayorCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mayorCheckActionPerformed
        menorCheck.setSelected(false);
        igualCheck.setSelected(false);
        
    }//GEN-LAST:event_mayorCheckActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //
        jButton2.setEnabled(true);
        switch(jComboBox1.getSelectedItem().toString()){
            case "Nombre":
                JOptionPane.showMessageDialog(null, "Nombre");
                campoNombre.setEnabled(true);
                campoProfesion.setEnabled(false);
                campoPromedio.setEnabled(false);
                break;
            case "Profesion":
                JOptionPane.showMessageDialog(null, "Profesion");
                campoNombre.setEnabled(false);
                campoProfesion.setEnabled(true);
                campoPromedio.setEnabled(false);
                break;
            case "Promedio":
                JOptionPane.showMessageDialog(null, "Promedio");
                campoNombre.setEnabled(false);
                campoProfesion.setEnabled(false);
                campoPromedio.setEnabled(true);
                break;
            case "Nombre/Profesion":
                JOptionPane.showMessageDialog(null, "Nombre/Profesion");
                campoNombre.setEnabled(true);
                campoProfesion.setEnabled(true);
                campoPromedio.setEnabled(false);
                break;
            case "Nombre/Promedio":
                JOptionPane.showMessageDialog(null, "Nombre/Promedio");
                campoNombre.setEnabled(true);
                campoProfesion.setEnabled(false);
                campoPromedio.setEnabled(true);
                
                break;
            case "Profesion/Nombre":
                JOptionPane.showMessageDialog(null, "Profesion/Nombre");
                campoProfesion.setEnabled(true);
                campoNombre.setEnabled(true);
                campoPromedio.setEnabled(false);
                break;
            case "Profesion/Promedio":
                JOptionPane.showMessageDialog(null, "Profesion/Promedio");
                campoProfesion.setEnabled(true);
                campoPromedio.setEnabled(true);
                campoNombre.setEnabled(false);
                break;
        }
        jButton1.setEnabled(false);
        jButton1.setEnabled(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
        //Codigo para buscar y leer los campos de texto (AQUI SE LLAMA LA FUNCION PARA BUSCAR)
        switch(jComboBox1.getSelectedItem().toString()){
            case "Nombre":
                JOptionPane.showMessageDialog(null, "Nombre");
                campoNombre.getText();
                
                break;
            case "Profesion":
                JOptionPane.showMessageDialog(null, "Profesion");
                
                campoProfesion.getText();
                
                break;
            case "Promedio":
                JOptionPane.showMessageDialog(null, "Promedio");
                
                campoPromedio.getText();//Parsear al tipo de dato de sus funciones
                break;
            case "Nombre/Profesion":
                JOptionPane.showMessageDialog(null, "Nombre/Profesion");
                campoNombre.getText();
                campoProfesion.getText();
                
                break;
            case "Nombre/Promedio":
                JOptionPane.showMessageDialog(null, "Nombre/Promedio");
                campoNombre.getText();
                
                campoPromedio.getText();//Parsear al tipo de dato de sus funciones
                
                break;
            case "Profesion/Nombre":
                JOptionPane.showMessageDialog(null, "Profesion/Nombre");
                campoProfesion.getText();
                campoNombre.getText();
                
                break;
            case "Profesion/Promedio":
                JOptionPane.showMessageDialog(null, "Profesion/Promedio");
                campoProfesion.getText();
                campoPromedio.getText();//Parsear al tipo de dato de sus funciones
                
                break;
        }
        jButton2.setEnabled(false);
        jButton2.setEnabled(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void menorCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menorCheckActionPerformed
        mayorCheck.setSelected(false);
        igualCheck.setSelected(false);
    }//GEN-LAST:event_menorCheckActionPerformed

    private void igualCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_igualCheckActionPerformed
        mayorCheck.setSelected(false);
        menorCheck.setSelected(false);
    }//GEN-LAST:event_igualCheckActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Busqueda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Busqueda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Busqueda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Busqueda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Busqueda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField campoNombre;
    private javax.swing.JTextField campoProfesion;
    private javax.swing.JTextField campoPromedio;
    private javax.swing.JCheckBox igualCheck;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JCheckBox mayorCheck;
    private javax.swing.JCheckBox menorCheck;
    // End of variables declaration//GEN-END:variables
}
